---
platform: linux

inputs:
- name: state

params:
  # credentials to talk to credhub server
  CREDHUB_CA_CERT:
  CREDHUB_CLIENT:
  CREDHUB_SECRET:
  CREDHUB_SERVER:

  # prefix flag used by credhub interpolate
  PREFIX:

  # other properties
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  ENV_NAME:

run:
  path: sh
  args:
  - "-c"
  - |
    set -euo pipefail

    # NOTE: The credhub cli does not ignore empty/null environment variables.
    # https://github.com/cloudfoundry-incubator/credhub-cli/issues/68
    if [ -z "$CREDHUB_CA_CERT" ]; then
      unset CREDHUB_CA_CERT
    fi

    credhub --version

    if [ -z "$PREFIX" ]; then
      echo "Please specify a PREFIX. It is required."
      exit 1
    fi

    cd state

    #######################################################
    echo "setting up opsmanager properties in credhub..."
    #######################################################

    credhub set -t value -n ${PREFIX}/pcf_aws_region \
    -v $(terraform output --json | jq -r .region.value)

    credhub set -t value -n ${PREFIX}/opsman_vpc_subnet_id \
    -v $(terraform output --json | jq -r .public_subnet_ids.value[0])

    credhub set -t value -n ${PREFIX}/opsman_security_group_id \
    -v $(terraform output --json | jq -r .ops_manager_security_group_id.value)

    credhub set -t value -n ${PREFIX}/opsman_ssh_public_key_name \
    -v $(terraform output --json | jq -r .ops_manager_ssh_public_key_name.value)

    credhub set -t value -n ${PREFIX}/opsman_public_ip \
    -v $(terraform output --json | jq -r .ops_manager_public_ip.value)

    credhub set -t value -n ${PREFIX}/ops_manager_iam_instance_profile_name \
    -v $(terraform output --json | jq -r .ops_manager_iam_instance_profile_name.value)

    credhub set -t value -n ${PREFIX}/opsman_domain \
    -v $(terraform output --json | jq -r .ops_manager_dns.value)

    ################################################################
    echo "setting up opsman director properties in credhub..."
    ################################################################

    credhub set -t value -n ${PREFIX}/iaas-configuration_access_key_id \
    -v ${AWS_ACCESS_KEY_ID}

    credhub set -t value -n ${PREFIX}/iaas-configuration_secret_access_key \
    -v ${AWS_SECRET_ACCESS_KEY}

    credhub set -t value -n ${PREFIX}/iaas-configuration_key_pair_name \
    -v $(terraform output --json | jq -r .ops_manager_ssh_public_key_name.value)

    credhub set -t value -n ${PREFIX}/iaas-configuration_region \
    -v $(terraform output --json | jq -r .region.value)

    credhub set -t value -n ${PREFIX}/iaas-configuration_security_group \
    -v $(terraform output --json | jq -r .vms_security_group_id.value)

    credhub set -t value -n ${PREFIX}/iaas-configuration_name \
    -v ${ENV_NAME}

    terraform output --json | jq -r .ops_manager_ssh_private_key.value > /tmp/ops_manager_ssh_private_key
    terraform output --json | jq -r .ops_manager_ssh_public_key.value > /tmp/ops_manager_ssh_public_key
    credhub set -t ssh -n ${PREFIX}/opsman-ssh-key \
    --private /tmp/ops_manager_ssh_private_key \
    --public /tmp/ops_manager_ssh_public_key

    rm /tmp/ops_manager_ssh_public_key /tmp/ops_manager_ssh_private_key

    ###############################################################
    echo "setting up azs properties in credhub....."
    ###############################################################

    credhub set -t value -n ${PREFIX}/singleton_availability_zone \
    -v $(terraform output --json | jq -r .infrastructure_subnet_availability_zones.value[0])

    credhub set -t value -n ${PREFIX}/az1 \
    -v $(terraform output --json | jq -r .infrastructure_subnet_availability_zones.value[0])

    credhub set -t value -n ${PREFIX}/az2 \
    -v $(terraform output --json | jq -r .infrastructure_subnet_availability_zones.value[1])

    credhub set -t value -n ${PREFIX}/az3 \
    -v $(terraform output --json | jq -r .infrastructure_subnet_availability_zones.value[2])

    ###############################################################
    echo "setting up network properties in credhub....."
    ###############################################################

    #infrastructure network properties

    credhub set -t value -n ${PREFIX}/infrastructure_subnet_cidrs_az1 \
    -v $(terraform output --json | jq -r .infrastructure_subnet_cidrs.value[0])

    credhub set -t value -n ${PREFIX}/infrastructure_subnet_ids_az1 \
    -v $(terraform output --json | jq -r .infrastructure_subnet_ids.value[0])

    credhub set -t value -n ${PREFIX}/infrastructure_subnet_gateways_az1 \
    -v $(terraform output --json | jq -r .infrastructure_subnet_gateways.value[0])

    credhub set -t value -n ${PREFIX}/infrastructure_subnet_reserved_ips_az1 \
    -v $(terraform output --json | jq -r .infrastructure_subnet_reserved_ips.value[0])

    #pas network properties

    credhub set -t value -n ${PREFIX}/pas_subnet_cidrs_az1 \
    -v $(terraform output --json | jq -r .pas_subnet_cidrs.value[0])

    credhub set -t value -n ${PREFIX}/pas_subnet_cidrs_az2 \
    -v $(terraform output --json | jq -r .pas_subnet_cidrs.value[1])

    credhub set -t value -n ${PREFIX}/pas_subnet_cidrs_az3 \
    -v $(terraform output --json | jq -r .pas_subnet_cidrs.value[2])

    credhub set -t value -n ${PREFIX}/pas_subnet_ids_az1 \
    -v $(terraform output --json | jq -r .pas_subnet_ids.value[0])

    credhub set -t value -n ${PREFIX}/pas_subnet_ids_az2 \
    -v $(terraform output --json | jq -r .pas_subnet_ids.value[1])

    credhub set -t value -n ${PREFIX}/pas_subnet_ids_az3 \
    -v $(terraform output --json | jq -r .pas_subnet_ids.value[2])

    credhub set -t value -n ${PREFIX}/pas_subnet_gateways_az1 \
    -v $(terraform output --json | jq -r .pas_subnet_gateways.value[0])

    credhub set -t value -n ${PREFIX}/pas_subnet_gateways_az2 \
    -v $(terraform output --json | jq -r .pas_subnet_gateways.value[1])

    credhub set -t value -n ${PREFIX}/pas_subnet_gateways_az3 \
    -v $(terraform output --json | jq -r .pas_subnet_gateways.value[2])

    credhub set -t value -n ${PREFIX}/pas_subnet_reserved_ips_az1 \
    -v $(terraform output --json | jq -r .pas_subnet_reserved_ips.value[0])

    credhub set -t value -n ${PREFIX}/pas_subnet_reserved_ips_az2 \
    -v $(terraform output --json | jq -r .pas_subnet_reserved_ips.value[1])

    credhub set -t value -n ${PREFIX}/pas_subnet_reserved_ips_az3 \
    -v $(terraform output --json | jq -r .pas_subnet_reserved_ips.value[2])

    #services network properties

    credhub set -t value -n ${PREFIX}/services_subnet_cidrs_az1 \
    -v $(terraform output --json | jq -r .services_subnet_cidrs.value[0])

    credhub set -t value -n ${PREFIX}/services_subnet_cidrs_az2 \
    -v $(terraform output --json | jq -r .services_subnet_cidrs.value[1])

    credhub set -t value -n ${PREFIX}/services_subnet_cidrs_az3 \
    -v $(terraform output --json | jq -r .services_subnet_cidrs.value[2])

    credhub set -t value -n ${PREFIX}/services_subnet_ids_az1 \
    -v $(terraform output --json | jq -r .services_subnet_ids.value[0])

    credhub set -t value -n ${PREFIX}/services_subnet_ids_az2 \
    -v $(terraform output --json | jq -r .services_subnet_ids.value[1])

    credhub set -t value -n ${PREFIX}/services_subnet_ids_az3 \
    -v $(terraform output --json | jq -r .services_subnet_ids.value[2])

    credhub set -t value -n ${PREFIX}/services_subnet_gateways_az1 \
    -v $(terraform output --json | jq -r .services_subnet_gateways.value[0])

    credhub set -t value -n ${PREFIX}/services_subnet_gateways_az2 \
    -v $(terraform output --json | jq -r .services_subnet_gateways.value[1])

    credhub set -t value -n ${PREFIX}/services_subnet_gateways_az3 \
    -v $(terraform output --json | jq -r .services_subnet_gateways.value[2])

    credhub set -t value -n ${PREFIX}/services_subnet_reserved_ips_az1 \
    -v $(terraform output --json | jq -r .services_subnet_reserved_ips.value[0])

    credhub set -t value -n ${PREFIX}/services_subnet_reserved_ips_az2 \
    -v $(terraform output --json | jq -r .services_subnet_reserved_ips.value[1])

    credhub set -t value -n ${PREFIX}/services_subnet_reserved_ips_az3 \
    -v $(terraform output --json | jq -r .services_subnet_reserved_ips.value[2])
