---
platform: linux

inputs:
- name: config # contains the env file with target OpsMan Information
- name: state
- name: terraforming

outputs:
- name: generated-state

params:
  TFVARS_FILE: terraform.tfvars
  # - Filepath of the env config YAML
  # - The path is relative to root of the `env` input

run:
  path: sh
  args:
  - "-c"
  - |

    terraform init terraforming/terraforming-pas

    terraform plan \
      -state state/terraform.tfstate \
      -out pcf.tfplan \
      -var-file "config/${TFVARS_FILE}" \
      terraforming/terraforming-pas

    terraform apply \
      -state-out generated-state/terraform.tfstate \
      pcf.tfplan
