resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: pcf-automation-tasks
  type: s3
  source:
    access_key_id: ((aws_access_key_id))
    bucket: ((s3_buckets_automation_products))
    secret_access_key: ((aws_secret_access_key))
    regexp: platform-automation-tasks-(.*).zip
    region_name: ((region))
    skip_ssl_verification: true

- name: pcf-automation-image
  type: s3
  source:
    access_key_id: ((aws_access_key_id))
    bucket: ((s3_buckets_automation_products))
    secret_access_key: ((aws_secret_access_key))
    regexp: platform-automation-image-(.*).tgz
    region_name: ((region))
    skip_ssl_verification: true

- name: installation
  type: s3
  source:
    access_key_id: ((aws_access_key_id))
    bucket: opsman-installation
    secret_access_key: ((aws_secret_access_key))
    regexp: ((foundation))/installation-(.*).zip
    region_name: ((region))
    skip_ssl_verification: true

- name: configuration
  type: git
  source:
    uri: git@github.com:ronakbanka/platform-automation.git
    branch: master
    private_key: ((git-private-key.private_key))

- name: opsman-image
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: ops-manager
    product_version: 2.7.*
    sort_by: semver

#credhub interpolate properties
credhub-interpolate: &credhub-interpolate
  image: pcf-automation-image
  file: pcf-automation-tasks/tasks/credhub-interpolate.yml
  input_mapping:
    files: configuration
  output_mapping:
    interpolated-files: config
  params:
    CREDHUB_CA_CERT: ((credhub_ca_cert.ca))
    CREDHUB_CLIENT: ((credhub_client))
    CREDHUB_SECRET: ((credhub_secret))
    CREDHUB_SERVER: ((credhub_server))
    PREFIX: /concourse/((foundation))
    INTERPOLATION_PATH: ((foundation))


jobs:
- name: upgrade-opsmanager
  serial: true
  plan:
  - aggregate:
    - get: pcf-automation-image
      params:
        unpack: true
    - get: pcf-automation-tasks
      params:
        unpack: true
    - get: configuration
    - get: opsman-image
      trigger: true
      params:
        globs:
        - 'ops-manager-aws-*.yml'
  - task: credhub-interpolate
    <<: *credhub-interpolate
  - task: export-installation
    image: pcf-automation-image
    file: pcf-automation-tasks/tasks/export-installation.yml
    input_mapping:
      env: config
    params:
      ENV_FILE: ((foundation))/env/env.yml
      INSTALLATION_FILE: installation-$timestamp.zip
  - put: installation
    params:
      file: installation/installation*.zip
  - task: upgrade-opsman
    image: pcf-automation-image
    file: pcf-automation-tasks/tasks/upgrade-opsman.yml
    input_mapping:
      image: opsman-image
      state: config
      config: config
      env: config
    params:
      ENV_FILE: ((foundation))/env/env.yml
      OPSMAN_CONFIG_FILE: ((foundation))/config/opsman.yml
      STATE_FILE: ((foundation))/state/state.yml
    ensure: &make-state-commit
      do:
        - task: make-commit
          image: pcf-automation-image
          file: pcf-automation-tasks/tasks/make-git-commit.yml
          input_mapping:
            repository: configuration
            file-source: generated-state
          output_mapping:
            repository-commit: configuration-commit
          params:
            FILE_SOURCE_PATH: state.yml
            FILE_DESTINATION_PATH: ((foundation))/state/state.yml
            GIT_AUTHOR_EMAIL: "pcf-automation-bot@ronakbanka"
            GIT_AUTHOR_NAME: "PCF Automation Bot"
            COMMIT_MESSAGE: 'Update state file'
        - put: configuration
          params:
            repository: configuration-commit
            merge: true
  - task: apply-director-changes
    image: pcf-automation-image
    file: pcf-automation-tasks/tasks/apply-director-changes.yml
    input_mapping:
      env: config
    params:
      ENV_FILE: ((foundation))/env/env.yml
  - task: after-upgrade-export-installation
    image: pcf-automation-image
    file: pcf-automation-tasks/tasks/export-installation.yml
    input_mapping:
      env: config
    params:
      ENV_FILE: ((foundation))/env/env.yml
      INSTALLATION_FILE: installation-$timestamp.zip
  - put: installation
    params:
      file: installation/installation*.zip
