---
opsman-configuration:
  gcp:
    gcp_service_account: |
      ((pcf_gcp_service_account))
    project: ((pcf_gcp_project))
    region: asia-southeast1
    zone: asia-southeast1-a
    vm_name: ops-manager-vm
    vpc_subnet: ((opsman_vpc_subnet_id))
    tags: ops-manager
    custom_cpu: 2
    custom_memory: 8
    boot_disk_size: 100
    public_ip: ((opsman_public_ip))
